#!/bin/bash
rootexample=${PWD}
exemdff=mdff.x

echo "-----------------------------------------------------------------"
echo "EXAMPLE 3 : "
echo "Global optimisation of clusters"
echo "Random structures are generated"
echo "and Local minima ( m1qn3 or lbfgs ) are found for each of them"
echo "better method has to be used for larger cluster"
echo "-----------------------------------------------------------------"

rep=runs
if [ -d $rep ] 
then
	rm -r $rep 
	mkdir -p $rep
else
	mkdir -p $rep
fi
cd $rep
	cp ${rootexample}/config/control_opt.F .
	cp ${rootexample}/config/run.py .
	./run.py --natm $1
        fftoxyz.py -i ISCFF.min -o ISCFF.xyz
        rasmol -ballstick -xyz ISCFF.xyz 
cd ..

