#!/bin/bash
# ====================================================
# user settings
export OMP_NUM_THREADS=1
description="Example 08 : NPT_I lennard jones argon (against DLPOLY,CP2K)"
example=${description%:*}
execp2k=cp2k
exemdff=mdff.x
exedlpoly=DLPOLY.X
cp2k=true
mdff=true
dlpoly=true
# ====================================================
rootexample=${PWD}
ensemble=npt
echo "--------------------------------------------------------------"
echo -e ${description} 
echo "--------------------------------------------------------------"
for code in dlpoly cp2k mdff
do
    if ${!code}
    then
        exe=exe${code}
        echo "running ${code} test ${example}"
        rm -rf ${code} 
        mkdir -p ${code}
        cd ${code}
        if [ ${code} == "cp2k" ]
        then
            cp ${rootexample}/config/argon*.inp .
	    cp ${rootexample}/config/control_gr.F .
            for run in 1 2 3
            do
	        mpirun -np 2 ${!exe} -i argon_${run}.inp -o argon_${run}.out
                xyztoff -i argon-pos-1.xyz 
	        mpirun -np 2 ${exemdff} control_gr.F > /dev/null
                mv GRTFF GRTFF_${run}.${ensemble}
                rm argon-pos-1.xyz
            done
        fi
        if [ ${code} == "dlpoly" ]
        then
	    cp ${rootexample}/config/CONFIG .
	    cp ${rootexample}/config/CONTROL* .
	    cp ${rootexample}/config/FIELD .
            for run in 1 2 3
            do 
                cp CONTROL_${run} CONTROL
	        ${!exe} 
	        tail -n +4 RDFDAT > RDFDAT_${run}.${ensemble}
            done
        fi
        if [ ${code} == "mdff" ]
        then
	    cp ${rootexample}/config/control_* .
	    cp ${rootexample}/config/POSFF .
            for run in 1 2 3
            do
	        mpirun -np 2 ${!exe} control_md_${run}.F > stdout_md
	        mpirun -np 2 ${!exe} control_gr.F > /dev/null
                mv GRTFF GRTFF_${run}.${ensemble}
            done
        fi
        cd ..
    fi
done

cat > comp_dlpoly.gr << eof
#!/usr/bin/gnuplot --persist 
reset
set term x11 font 'Consola,28' linewidth 3
p for [i=1:3] 'mdff/GRTFF_'.i.'.npt' w l title "MDFF".i,\
  for [i=1:3] 'cp2k/GRTFF_'.i.'.npt' w l title "CP2K".i
pause -1
eof
chmod u+x comp_dlpoly.gr
./comp_dlpoly.gr

cat > comp_cp2k.gr << eof
#!/usr/bin/gnuplot --persist 
reset
set term x11 font 'Consola,28' linewidth 3
p for [i=1:3] 'mdff/GRTFF_'.i.'.npt' w l title "MDFF".i,\\
  for [i=1:3] 'cp2k/GRTFF_'.i.'.npt' w l title "CP2K".i
pause -1
eof
chmod u+x comp_cp2k.gr
./comp_cp2k.gr
