#!/bin/bash
# ====================================================
# user settings
export OMP_NUM_THREADS=1
description="Example 07 : NVT (Nose Hoover Chain) lennard jones argon (against CP2K)"
execp2k=cp2k
exemdff=mdff.x
cp2k=true
mdff=true
# ====================================================
rootexample=${PWD}
example=${description%:*}
echo "-----------------------------------------------"
echo -e ${description} 
echo "-----------------------------------------------"
for code in cp2k mdff
do
    if ${!code}
    then
        exe=exe${code}
        echo "running ${code} test ${example}"
        rm -rf ${code} 
        mkdir -p ${code}
        cd ${code}
        if [ ${code} == "cp2k" ]
        then
            cp ${rootexample}/config/argon*.inp .
	    cp ${rootexample}/config/control_gr.F .
            for run in 1 2
            do
	        mpirun -np 2 ${!exe} -i argon_${run}.inp -o argon_${run}.out
                xyztoff -i argon-pos-1.xyz 
	        mpirun -np 2 ${exemdff} control_gr.F > /dev/null
                mv GRTFF GRTFF.${run}
                rm argon-pos-1.xyz
            done
        fi
        if [ ${code} == "mdff" ]
        then
	    cp ${rootexample}/config/control_* .
	    cp ${rootexample}/config/POSFF .
            for run in 1 2
            do
	        mpirun -np 2 ${!exe} control_md_${run}.F > stdout_md_${run}
	        mpirun -np 2 ${!exe} control_gr.F > /dev/null
                mv GRTFF GRTFF.${run}
            done
        fi
        cd ..
    fi
done

cat > plot.gr << eof
#!/usr/bin/gnuplot
reset
p 'cp2k/GRTFF.1' w l title "CP2K 221",'mdff/GRTFF.1' w l title "MDFF 221",\
  'cp2k/GRTFF.2' w l title "CP2K 332",'mdff/GRTFF.2' w l title "MDFF 332"
pause -1
eof
chmod u+x plot.gr
./plot.gr

