#!/bin/bash
export OMP_NUM_THREADS=1

exercice="ex06"
rootexe=${PWD}

exedlpoly=DLPOLY.X
exemdff=mdff.x

dlpoly=true
mdff=true

for code in dlpoly mdff
do
    if ${!code}
    then
        exe=exe${code}
        echo "running ${code} test ${exercice}"
        rm -rf ${code} 
        mkdir -p ${code}
        cd ${code}
        if [ ${code} == "dlpoly" ]
        then
            cp ${rootexe}/config/CONFIG .
            cp ${rootexe}/config/CONTROL .
            cp ${rootexe}/config/FIELD .
            ${!exe}
            tail -n +4 RDFDAT > RDFDAT.tmp
        fi
        if [ ${code} == "mdff" ]
        then
	    cp ${rootexe}/config/control_* .
	    cp ${rootexe}/config/POSFF .
	    mpirun -np 2 ${!exe} control_md.F > stdout_md
	    mpirun -np 2 ${!exe} control_gr.F > stdout_gr
        fi
        cd ..
    fi
done

cat > plot.gr << eof
#!/usr/bin/gnuplot
reset
p 'dlpoly/RDFDAT.tmp' w l ,'mdff/GRTFF' w l
pause -1
eof
chmod u+x plot.gr
./plot.gr

