#!/bin/bash
# ====================================================
# user settings
export OMP_NUM_THREADS=1
description="NVT (Nose Hoover) lennard jones argon (against DLPOLY)" 
exedlpoly=DLPOLY.X
exemdff=mdff.x
dlpoly=true
mdff=true
# ====================================================
rootexample=${PWD}
example=${description%:*}
echo "----------------------------------------------------------"
echo -e ${description} 
echo "----------------------------------------------------------"
for code in dlpoly mdff
do
    if ${!code}
    then
        exe=exe${code}
        echo "running ${code} test ${example}"
        rm -rf ${code} 
        mkdir -p ${code}
        cd ${code}
        if [ ${code} == "dlpoly" ]
        then
            cp ${rootexample}/config/CONFIG .
            cp ${rootexample}/config/CONTROL .
            cp ${rootexample}/config/FIELD .
            ${!exe}
            tail -n +4 RDFDAT > RDFDAT.tmp
        fi
        if [ ${code} == "mdff" ]
        then
	    cp ${rootexample}/config/control_* .
	    cp ${rootexample}/config/POSFF .
	    mpirun -np 2 ${!exe} control_md.F > stdout_md
	    mpirun -np 2 ${!exe} control_gr.F > stdout_gr
        fi
        cd ..
    fi
done

cat > plot.gr << eof
#!/usr/bin/gnuplot
reset
p 'dlpoly/RDFDAT.tmp' w l ,'mdff/GRTFF' w l
pause -1
eof
chmod u+x plot.gr
./plot.gr

